- name: add sbt repo
  command: echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list

- name: add sbt key
  apt_key: 
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823

- name: install sbt
  apt:
    name: sbt
    update_cache: yes


